### ISSUE TITLE
代码没有考虑漏签的情况

### ISSUE THREAD

**Issue by cibimo** [libuke/aliyundrive-checkin#12]
current_datetime = datetime.datetime.now(shanghai_timezone)
day = current_datetime.day

rewards = filter(lambda info: int(info.get('day', 0)) == day, signInInfos)

这里代码没有考虑漏签的情况

**Comment by cibimo** [comment]
改为
rewards = filter(lambda info: int(info.get('day', 0)) == data['result']['signInCount'], signInInfos)
？

**Comment by libuke** [comment]
好，我改了测试下

**Comment by libuke** [comment]
修改了
