### ISSUE TITLE
奖励任务（开启备份一个小时）是不是无法签到成功啊

### ISSUE THREAD

**Issue by kinshupoon** [libuke/aliyundrive-checkin#13]
感觉每次都领取失败，然后需要打开手机app或者电脑客户端，再次执行才能领取。这个奖励任务是不能自动执行吗？有没有办法不用手机或电脑也能完成每天的奖励任务。

**Comment by libuke** [comment]
阿里云盘分为签到奖励和做任务奖励，目前无法自动做任务。只能看到今天的任务和奖励
