### ISSUE TITLE
工作流运行报错

### ISSUE THREAD

**Issue by zhtjtcz** [libuke/aliyundrive-checkin#37]
运行到 gautamkrishnar/keepalive-workflow@master 时，出现以下报错信息：

`
Error: {"command":"git push origin HEAD","exitCode":128,"outputData":"","errorData":"remote: Permission to zhtjtcz/aliyundrive-checkin.git denied to github-actions[bot].\nfatal: unable to access 'https://github.com/zhtjtcz/aliyundrive-checkin.git/': The requested URL returned error: 403\n"}
`

重复执行也是一样结果。
此外，似乎阿里云盘最近修改了签到的逻辑？签到成功的奖励还需要手动点击领取，请问有计划更新一下action吗？

**Comment by libuke** [comment]
可以参考一下 [https://stackoverflow.com/questions/73687176/permission-denied-to-github-actionsbot-the-requested-url-returned-error-403](https://stackoverflow.com/questions/73687176/permission-denied-to-github-actionsbot-the-requested-url-returned-error-403)

**Comment by libuke** [comment]
工作流运行报错已修复，如果还是提示这个错误。参考一下上面的链接
