### ISSUE TITLE
这个错误怎么解决

### ISSUE THREAD

**Issue by yzw20020919** [libuke/aliyundrive-checkin#4]
![屏幕截图 2023-09-25 021417](https://github.com/libuke/aliyundrive-checkin/assets/86851790/af869280-f542-414a-8de6-ffbca102f73a)

**Comment by libuke** [comment]
可以参考一下 [https://stackoverflow.com/questions/73687176/permission-denied-to-github-actionsbot-the-requested-url-returned-error-403](https://stackoverflow.com/questions/73687176/permission-denied-to-github-actionsbot-the-requested-url-returned-error-403)
