### ISSUE TITLE
签到失败

### ISSUE THREAD

**Issue by i2000** [libuke/aliyundrive-checkin#5]
签到失败
错误信息：Unexpected error occurred: RetryError[<Future at 0x7f7654849e40 state=finished raised ReadTimeout>]
请问这个错误怎么解决

**Comment by libuke** [comment]
重新获取一下阿里云盘Token

**Comment by libuke** [comment]
之前有遇到过，每次出现这个错误重新获取一下阿里云盘token就好了。后面会把这个失败提示改一下

可以把代码下载到本地

`python3 main.py --token_string 'token'`

用print() 或者 断点排查一下

**Comment by i2000** [comment]
没问题了，不用修改 Token，只是启动时签到失败，后面自动签到成功了
