### ISSUE TITLE
只能获取每日任务不能领取吗

### ISSUE THREAD

**Issue by windy1021** [libuke/aliyundrive-checkin#8]
签到成功但是只能领取第一个任务的奖励，就算第二个任务已经处于课领取状态也没有领取，希望大佬可以让他自动领取

**Comment by libuke** [comment]
目前只能领取任务，还无法自动做任务领取奖励。我技术不够，这个自动完成任务搞不了

**Comment by windy1021** [comment]
> 目前只能领取任务，还无法自动做任务领取奖励。我技术不够，这个自动完成任务搞不了

好的，谢谢大大
